# University of Kentucky Center for Poverty Research (UKCPR)

[National Welfare Data](https://ukcpr.uky.edu/resources)

In [1]:
import pandas as pd

# Set the maximum number of rows to display to 'None' (unlimited)
pd.set_option('display.max_rows', None)

# Optional: Also ensure column names don't get truncated
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [2]:
df = pd.read_excel("../../data/Nat_Welfare_Data_1980_2024.xlsx", sheet_name="Data")
df.head()

,state_name,state,state_fips,year,Population,Employment,Unemployment,Unemployment rate,Marginally Food Insecure,Food Insecure,Very Low Food Secure,Gross State Product,Number of low income uninsured children,Percent Low Income Unisured Children,Personal income,Workers' compensation,AFDC/TANF Recipients,AFDC/TANF Caseloads,Food Stamp/SNAP Recipients,Food Stamp/SNAP Caseloads,AFDC/TANF Benefit for 2-Person family,AFDC/TANF Benefit for 3-person family,AFDC/TANF benefit for 4-person family,FS/SNAP Benefit for 1-person family,FS/SNAP Benefit for 2-person family,FS/SNAP Benefit for 3-person family,FS/SNAP Benefit for 4-person family,AFDC/TANF_FS 2-Person Benefit,AFDC/TANF_FS 3-Person Benefit,AFDC/TANF_FS 4-Person Benefit,Child-only AFDC/TANF cases,SSI-Federal,SSI-State,Total SSI,SSI_FS Benefit,Number of Poor (thousands),Poverty Rate,Governor is Democrat (1=Yes),Number in Lower House Democrat,Number in Lower House Republican,Fraction of State House that is Democrat,Number in Upper House Democrat,Number in Upper House Republican,Fraction of State Senate that is Democrat,EITC Phase-In Rate No Dependents,EITC Phase-In Rate 1 Dependent,EITC Phase-In Rate 2 Dependents,EITC Phase-In Rate 3 Dependents,EITC Maximum Credit No Dependents,EITC Maximum Credit 1 Dependent,EITC Maximum Credit 2 Dependents,EITC Maximum Credit 3 Dependents,EITC Phase-Out Rate No Dependents,EITC Phase-Out Rate 1 Dependent,EITC Phase-Out Rate 2 Dependents,EITC Phase-Out Rate 3 Dependents,State EITC Rate,Wisconsin EITC Rate 2 Dependents,Wisconsin EITC Rate 3 Dependents,Refundable State EITC (1=Yes),Federal Minimum Wage,State Minimum Wage,SSI recipients,SSI recipients--Aged,SSI recipients--Blind,SSI recipients--Disabled,Medicaid beneficiaries,WIC participation,NSLP Free Participation,NSLP Reduced Participation,NSLP Total Participation,SBP Free Participation,SBP Reduced Participation,SBP Total Participation,Fraction of the Year ACA Expansion
0,AL,1,1,1980,3893888,1521183,148106,8.9,NaN,NaN,NaN,36142.0,NaN,NaN,31037100.0,15220,179602.0,62733.0,582862.80,193482.800,89.0,118.0,148.0,63,115,165,209,204.0,283.0,357.0,NaN,238,0.0,238.0,279.0,810,21.2,1,101.0,4.0,0.96,35.0,0.0,1.000000,0.0,0.1,0.1,0.1,0,500,500,500,0.0,0.125,0.125,0.125,0.0,NaN,NaN,0.0,3.1,3.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,AK,2,2,1980,401851,169397,18008,9.6,NaN,NaN,NaN,15282.0,NaN,NaN,6285000.0,4897,15135.0,6158.0,28693.25,9837.167,400.0,457.0,514.0,98,180,258,327,564.0,681.0,790.0,NaN,238,235.0,473.0,533.0,36,9.6,0,25.0,14.0,0.64,9.0,11.0,0.450000,0.0,0.1,0.1,0.1,0,500,500,500,0.0,0.125,0.125,0.125,0.0,NaN,NaN,0.0,3.1,3.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,AZ,3,4,1980,2718215,1146371,81630,6.6,NaN,NaN,NaN,30764.0,NaN,NaN,26477600.0,60845,51245.0,18312.0,195560.40,65209.750,156.0,202.0,244.0,63,115,165,209,271.0,356.0,429.0,NaN,238,0.0,238.0,279.0,354,12.8,1,18.0,42.0,0.30,14.0,16.0,0.466667,0.0,0.1,0.1,0.1,0,500,500,500,0.0,0.125,0.125,0.125,0.0,NaN,NaN,0.0,3.1,3.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,AR,4,5,1980,2286435,922894,75386,7.6,NaN,NaN,NaN,20276.0,NaN,NaN,17388300.0,12021,84958.0,29457.0,300828.90,102997.800,133.0,161.0,188.0,63,115,165,209,248.0,326.0,390.0,NaN,238,0.0,238.0,279.0,484,21.5,1,94.0,6.0,0.94,35.0,0.0,1.000000,0.0,0.1,0.1,0.1,0,500,500,500,0.0,0.125,0.125,0.125,0.0,NaN,NaN,0.0,3.1,2.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,CA,5,6,1980,23667902,10787673,791379,6.8,NaN,NaN,NaN,327958.0,NaN,NaN,284308000.0,367598,1386871.0,476146.0,1492669.00,542672.200,382.0,473.0,563.0,63,115,165,209,432.0,546.0,653.0,NaN,238,182.0,420.0,407.0,2619,11.0,1,50.0,30.0,0.63,25.0,14.0,0.641026,0.0,0.1,0.1,0.1,0,500,500,500,0.0,0.125,0.125,0.125,0.0,NaN,NaN,0.0,3.1,3.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [3]:
# filter for 1999-2016
df = df[df["year"].between(1999, 2016)].reset_index(drop=True)

In [4]:
# Reduce to key features
cols_to_keep = [
    'state_name', 'year',                          # Keys
    'Population',                                  # Calculate Rates
    'Unemployment rate', 'Poverty Rate',                # Core Economics
    'Food Stamp/SNAP Recipients', 'Gross State Product',        # Financial Stress
    'Medicaid beneficiaries',                      # Healthcare
    'Fraction of the Year ACA Expansion',          # Policy Shift
    'Governor is Democrat (1=Yes)',                # Political Context
    'State Minimum Wage'                           # Economic Policy
]

df = df[cols_to_keep].copy()

col_names = ["state_abbr", "year", 
             "population",
             "unempl_rate", "poverty_rate",
             "snap_recipients", "gsp",
            "medicaid_beneficiaries",
            "aca_exp",
            "gov_dem",
            "min_wage"]

df.columns = col_names


df.head()

,state_abbr,year,population,unempl_rate,poverty_rate,snap_recipients,gsp,medicaid_beneficiaries,aca_exp,gov_dem,min_wage
0,AL,1999,4369862,4.7,15.2,405273.0,115833.1,516011,0.0,1,5.15
1,AK,1999,619500,6.5,7.6,41262.0,24779.3,74095,0.0,1,5.65
2,AZ,1999,4778332,4.4,12.2,257362.0,155282.6,455723,0.0,0,5.15
3,AR,1999,2551373,4.6,14.7,252957.0,66791.2,379518,0.0,0,5.15
4,CA,1999,33145121,5.2,14.0,2027089.0,1247734.4,5063102,0.0,1,5.75

In [5]:
# Calculate rates and drop raw counts
df['snap_rate'] = df['snap_recipients'] / df['population']
df['medicaid_rate'] = df['medicaid_beneficiaries'] / df['population']

df = df.drop(columns=['snap_recipients', 'medicaid_beneficiaries', 'population'])
df.head()

,state_abbr,year,unempl_rate,poverty_rate,gsp,aca_exp,gov_dem,min_wage,snap_rate,medicaid_rate
0,AL,1999,4.7,15.2,115833.1,0.0,1,5.15,0.092743,0.118084
1,AK,1999,6.5,7.6,24779.3,0.0,1,5.65,0.066605,0.119605
2,AZ,1999,4.4,12.2,155282.6,0.0,0,5.15,0.053860,0.095373
3,AR,1999,4.6,14.7,66791.2,0.0,0,5.15,0.099145,0.14875
4,CA,1999,5.2,14.0,1247734.4,0.0,1,5.75,0.061158,0.152756

In [6]:
df.isna().sum()

state_abbr       0
year             0
unempl_rate      0
poverty_rate     0
gsp              0
aca_exp          0
gov_dem          0
min_wage         0
snap_rate        0
medicaid_rate    0
dtype: int64

In [7]:
# Add full state names
state_mapping = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 
    'CA': 'California', 'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 
    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho', 
    'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas', 
    'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland', 
    'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi', 
    'MO': 'Missouri', 'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada', 
    'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico', 'NY': 'New York', 
    'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma', 
    'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina', 
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah', 
    'VT': 'Vermont', 'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia', 
    'WI': 'Wisconsin', 'WY': 'Wyoming', 'DC': 'District of Columbia'
}

df['state_name'] = df['state_abbr'].map(state_mapping)

In [8]:
# Define the logical order
ordered_cols = [
    # 1. Identifiers
    'state_name', 'state_abbr', 'year', 
    
    # 2. Economic Features (Macro-level stress)
    'poverty_rate', 'unempl_rate', 'gsp', 'min_wage',
    
    # 3. Social Safety Net & Healthcare (Policy indicators)
    'snap_rate', 'medicaid_rate', 'aca_exp',
    
    # 4. Political Context
    'gov_dem'
]

# Apply the reordering
df = df[ordered_cols]

# Display the result
df.head()

,state_name,state_abbr,year,poverty_rate,unempl_rate,gsp,min_wage,snap_rate,medicaid_rate,aca_exp,gov_dem
0,Alabama,AL,1999,15.2,4.7,115833.1,5.15,0.092743,0.118084,0.0,1
1,Alaska,AK,1999,7.6,6.5,24779.3,5.65,0.066605,0.119605,0.0,1
2,Arizona,AZ,1999,12.2,4.4,155282.6,5.15,0.053860,0.095373,0.0,0
3,Arkansas,AR,1999,14.7,4.6,66791.2,5.15,0.099145,0.14875,0.0,0
4,California,CA,1999,14.0,5.2,1247734.4,5.75,0.061158,0.152756,0.0,1

In [9]:
# Save cleaned data
df.to_csv("../../data/UKCPR_cleaned.csv", index=False)